# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  revision = "9e773d2dd46a9b113d94fb3c245231d231bcfeda"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
